name: Build and deploy an app to EKS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  CLUSTER_NAME: "qwerty_cluster"
jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_account_id }}:role/github_web_identity
          role-session-name: githubassumesession
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1


      # Builds and pushes an image up to your ECR
      - name: Build, tag, and push image to ECR
        id: build-image
        run: |
          # echo "....>>>>>>>>>logging in to ECR Repository<<<<<<<<<<<<<<....."
          #          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_account_id }}.dkr.ecr.us-east-1.amazonaws.com
          #echo "....>>>>>>>>>logging in to docker hub<<<<<<<<<<<<<<....."
          #docker login -u=${{ secrets.DOCKER_USERNAME }} -p=${{ secrets.DOCKER_PASSWORD }}

          echo Build started on `date`

          echo "....>>>>>>>>>Building the Docker image<<<<<<<<<<<<<<........"
          docker build -t httpd .
          docker tag httpd:${{ github.sha }} ${{ secrets.AWS_account_id }}.dkr.ecr.us-east-1.amazonaws.com/httpd:${{ github.sha }}
          # docker build -t baskarvj/httpdsample:${{ github.sha }} .
          
          
          echo "....>>>>>>>>>Pushing image to docker hub<<<<<<<<<<<<<<....."
          
          # docker push baskarvj/httpdsample:${{ github.sha }} 
          docker push 384834573830.dkr.ecr.us-east-1.amazonaws.com/httpd:${{ github.sha }}



  deploy:
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v3
  

      - name: Push Changes to argocd
        run: |
            git clone https://baskarvj:${{ secrets.git_pass }}@github.com/baskarvj/EKS_Compelete_setup.git
            cd EKS_Compelete_setup
            ls -la
            sed -i '/image: 384834573830.dkr.ecr.us-east-1.amazonaws.com/httpd.*/c\         image: 384834573830.dkr.ecr.us-east-1.amazonaws.com/httpd:${{ github.sha }}' manifest/deploy.yml
           
            cat manifest/deploy.yml
            
            git config user.email "baskeyvj03@gmail.com"
            git config user.name "baskarvj"

            git add .
            git commit -m "image updated"
            git push https://baskarvj:${{ secrets.git_pass }}@github.com/baskarvj/EKS_Compelete_setup.git
